repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: check-json
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: detect-private-key
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets

  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt
        language: rust
        pass_filenames: False

      - id: cargo-check
        name: cargo check
        entry: cargo check
        language: rust
        pass_filenames: False

      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy
        language: rust
        pass_filenames: False

      - id: cargo-test
        name: cargo test
        entry: cargo test
        language: rust
        pass_filenames: False
